#!/bin/bash
# 🚀 GUIA RÁPIDO - Sistema Bancário Educacional

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   🏦 SISTEMA BANCÁRIO EDUCACIONAL - SPRING BOOT           ║"
echo "║   Guia Rápido de Inicialização                             ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 PASSO 1: Verifique os pré-requisitos"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Requisitos:"
echo "  • Java 21+ (verificar: java -version)"
echo "  • Maven 3.8+ (verificar: mvn -version)"
echo "  • Git (verificar: git --version)"
echo ""

echo "📦 PASSO 2: Clone o repositório"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ git clone https://github.com/douglasrm87/JavaOOInteliJ.git"
echo "$ cd JavaOOInteliJ"
echo ""

echo "🔨 PASSO 3: Compile o projeto"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ mvn clean compile"
echo ""

echo "🚀 PASSO 4: Execute a aplicação"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ mvn spring-boot:run"
echo ""
echo "Ou via IDE:"
echo "  • IntelliJ: Click direito em ProjetoWEB.java → Run"
echo "  • Eclipse: Click direito em projeto → Run As → Spring Boot App"
echo ""

echo "🌐 PASSO 5: Acesse a aplicação"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "URL: http://localhost:8081"
echo ""

echo "🔐 PASSO 6: Faça login"
echo "━━━━━━━━━━━━━━━━━━━━"
echo "Usuário: drm"
echo "Senha: 12345"
echo ""

echo "📊 PASSO 7: Acesse o banco de dados (opcional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "URL: http://localhost:8081/h2-console"
echo "JDBC URL: jdbc:h2:mem:test"
echo "Usuário: sa"
echo "Senha: password"
echo ""

echo "🧪 PASSO 8: Teste as funcionalidades"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Login com drm/12345"
echo "2. Clique em 'Caixa Eletrônico'"
echo "3. Teste as operações:"
echo "   - Saque: Use conta 001234, agência 0001, CPF 123.456.789-00"
echo "   - Depósito: Use os mesmos dados"
echo "   - Extrato: Visualize histórico"
echo "   - Saldo: Consulte saldo atual"
echo "   - Cadastro: Crie uma nova conta"
echo ""

echo "📚 DOCUMENTAÇÃO"
echo "━━━━━━━━━━━━━"
echo "• README.md - Visão geral do projeto"
echo "• GUIA_APRENDIZADO.md - Tutorial estruturado"
echo "• MELHORIAS.md - O que foi melhorado"
echo "• STATUS.md - Status e checklist"
echo ""

echo "🆘 PROBLEMAS COMUNS"
echo "━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Erro: 'Java version not supported'"
echo "✅ Solução: Instale Java 21 (https://adoptium.net/)"
echo ""
echo "❌ Erro: 'Maven command not found'"
echo "✅ Solução: Instale Maven (https://maven.apache.org/)"
echo ""
echo "❌ Erro: 'Port 8081 already in use'"
echo "✅ Solução: Altere em application.properties:"
echo "   server.port=8082"
echo ""
echo "❌ Erro: 'Conexão recusada no banco de dados'"
echo "✅ Solução: H2 é in-memory, dados são perdidos ao reiniciar"
echo ""

echo "💡 DICAS"
echo "━━━━━━"
echo "• Use Ctrl+C para parar a aplicação"
echo "• Logs aparecem no console"
echo "• Sempre limpe o cache: mvn clean"
echo "• Use IDE para debug mais fácil"
echo ""

echo "✨ PRÓXIMOS PASSOS"
echo "━━━━━━━━━━━━━━━"
echo "1. Explore GUIA_APRENDIZADO.md para entender a arquitetura"
echo "2. Estude o código fonte"
echo "3. Implemente nova funcionalidade (ex: transferência)"
echo "4. Adicione seus próprios testes"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   ✅ Pronto para começar! Bom aprendizado! 🚀             ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
